<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'AndroidLintEngine' => 'lint/engine/AndroidLintEngine.php',
    'AndroidUnitTestEngine' => 'unit/AndroidUnitTestEngine.php',
    'ArcanistAndroidLinter' => 'lint/linter/ArcanistAndroidLinter.php',
    'ArcanistAndroidLinterTestCase' => 'lint/linter/__tests__/ArcanistAndroidLinterTestCase.php',
    'ArcanistCustomLicenseLinter' => 'lint/linter/ArcanistCustomLicenseLinter.php',
    'ArcanistMobileGeneratedLinter' => 'lint/linter/ArcanistMobileGeneratedLinter.php',
    'ArcanistMobileGeneratedLinterTestCase' => 'lint/linter/__tests__/ArcanistMobileGeneratedLinterTestCase.php',
    'ArcanistOCFilenameLinter' => 'lint/linter/ArcanistOCFilenameLinter.php',
    'ArcanistOCLinter' => 'lint/linter/ArcanistOCLinter.php',
    'ArcanistOCLinterTestCase' => 'lint/linter/__tests__/ArcanistOCLinterTestCase.php',
    'ArcanistOCStaticAnalysisLinter' => 'lint/linter/ArcanistOCStaticAnalysisLinter.php',
    'ArcanistReSharperLinter' => 'lint/linter/ArcanistReSharperLinter.php',
    'DotNetLintEngine' => 'lint/engine/DotNetLintEngine.php',
    'MobileLintEngine' => 'lint/engine/MobileLintEngine.php',
    'MobileUnitTestEngine' => 'unit/MobileUnitTestEngine.php',
    'OCLintEngine' => 'lint/engine/OCLintEngine.php',
    'OCUnitTestEngine' => 'unit/OCUnitTestEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'AndroidLintEngine' => 'ArcanistLintEngine',
    'AndroidUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
    'ArcanistAndroidLinter' => 'ArcanistLinter',
    'ArcanistAndroidLinterTestCase' => 'ArcanistLinterTestCase',
    'ArcanistCustomLicenseLinter' => 'ArcanistLinter',
    'ArcanistMobileGeneratedLinter' => 'ArcanistLinter',
    'ArcanistMobileGeneratedLinterTestCase' => 'ArcanistLinterTestCase',
    'ArcanistOCFilenameLinter' => 'ArcanistLinter',
    'ArcanistOCLinter' => 'ArcanistLinter',
    'ArcanistOCLinterTestCase' => 'ArcanistLinterTestCase',
    'ArcanistOCStaticAnalysisLinter' => 'ArcanistLinter',
    'ArcanistReSharperLinter' => 'ArcanistLinter',
    'DotNetLintEngine' => 'ArcanistLintEngine',
    'MobileLintEngine' => 'ArcanistLintEngine',
    'MobileUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
    'OCLintEngine' => 'ArcanistLintEngine',
    'OCUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
  ),
));
