<?php

/*

Copyright 2012-2015 iMobile3, LLC. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, is permitted provided that adherence to the following
conditions is maintained. If you do not agree with these terms,
please do not use, install, modify or redistribute this software.

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY IMOBILE3, LLC "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
EVENT SHALL IMOBILE3, LLC OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

/**
 * Stops other linters from running on generated code.
 *
 * @group linter
 */
final class ArcanistMobileGeneratedLinter extends ArcanistLinter {

    public function willLintPaths(array $paths) {
        return;
    }

    public function getLinterName() {
        return 'MobileGeneratedLint';
    }

    public function getLintSeverityMap() {
        return array();
    }

    public function getLintNameMap() {
        return array();
    }

    public function lintPath($path) {
        // minified JavaScript
        if (substr($path, -7) == '.min.js') {
            $this->stopAllLinters();
            return;
        }

        // minified CSS
        if (substr($path, -8) == '.min.css') {
            $this->stopAllLinters();
            return;
        }

        $path_on_disk = $this->getEngine()->getFilePathOnDisk($path);

        if ($this->getEngine()->isBinaryFile($path_on_disk)) {
            return;
        }

        $data = $this->getData($path_on_disk);

        if (preg_match('/@' . 'generated/', $data)) {
            $this->stopAllLinters();
            return;
        }

        $file_contents = file_get_contents($path_on_disk);
        if (strpos($file_contents, '<auto-generated>') !== false) {
            $this->stopAllLinters();
            return;
        }
    }
}
